### PR TITLE
Chunk pathnames_per_binary into segments that do not exceed the OS ARG_MAX size for calls to llvm-cov

### PR DESCRIPTION
**Pull request by weibel**
I have encountered the issue in https://github.com/SlatherOrg/slather/issues/243 which is not easily solvable. This is an attempt to fix the problem by chunking calls llvm cov into smaller segments which are recombined. I'll give it some time to see if there are any problems.

### CODE REVIEW

**Comment by weibel** [comment]
@dnedrow Coverage is back up.

**Comment by ksuther** [comment]
Thanks for this! Looks good to me, but it'd be nice to have confirmation from someone who was encountering the original problem. @diaojunxian, could you see if this solves the problem you encountered?

**Comment by weibel** [comment]
My main concerns with this is
* I don't have a good solution if ```getconf ARG_MAX``` does not work the system
* The effective usable size of an argument is harder to determine than the 10% padding I have put in https://www.in-ulm.de/~mascheck/various/argmax/

**Comment by weibel** [comment]
I have addressed my concerns with https://github.com/SlatherOrg/slather/pull/414/commits/ba4e9b1325e71bf660f2773f408c0c7967952ec8

**Comment by ksuther** [comment]
Thanks @weibel!

**Comment by stevebaxter** [comment]
Any chance of a release that includes this fix sometime soon? We're running in to this issue!

**Pull request merged**
