### PR TITLE
Support for manually specifing multiple binaries

### LINKED ISSUE #157: Support Multiple Binary Files
Our swift project has several dynamic libraries. When running UI tests, we exercise functionality in several of them.

It appears that slather requires one invocation per binary file at the moment. (or one .slather.yml per binary file).

Is there a way to produce coverage reports for a list of binary files or is this something that will have to be scripted?

### PR DESCRIPTION
**Pull request by ksuther**
`--binary-file` and `--binary-basename` parameters can now be used multiple times to specify multiple binaries.
The equivalent `binary_file` and `binary_basename` parameters in the config file can either be a string or an array.

Example usage:

`slather coverage --scheme MyScheme --binary-basename BinaryOne --binary-basename DynamicLibrary -s MyProject.xcodeproj`

This doesn't automatically detect all linked binaries and associated test targets. That's a lot more work, and it would also require having a way to exclude binaries that should be ignored for coverage. I don't know that the net benefit is very big.

Fixes #157.

### CODE REVIEW

**Comment by neonichu** [comment]
LGTM, I think we should add a test which explicitly has multiple binaries, though — also changelog entry of course :)

As to the limitations, I think those should be fine — this is in any case more flexible than the current implementation anyway :+1:

**Comment by ksuther** [comment]
Agreed on the multi-target test, I ran out of steam before I got to adding a new target to the test project.

**Comment by ksuther** [comment]
Added a second target to the test project to verify the changes.

**Comment by neonichu** [comment]
:shipit:

**Comment by TeresaP** [comment]
Thank you!!

**Pull request merged**
