### PR TITLE
Bump xcodeproj to 1.21

### PR DESCRIPTION
**Pull request by adamyanalunas**
👋 Hi there!

Between CocoaPods and Fastlane using more recent versions of xcodeproj I’m blocked from using Slather 2.7.1, the latest release.

This PR just bumps Slather’s xcodeproj dependency from 1.7 to 1.21. Easy peasy.

Let me know if there’s documentation or versioning or anything else I should add here. Thanks!

### CODE REVIEW

**Comment by ksuther** [comment]
Thanks for the PR! This conflicts because of another dependency update. Can you rebase the branch?

Also, should the dependency version be `1.21.0` or `1.21`? I'm not sure if `1.21.0` will lock it to `1.21.x` versions or not.

**Comment by adamyanalunas** [comment]
Good callout on locking to minor, not patch. Thanks, @ksuther!

Change made, conflict resolved 👍

**Comment by ksuther** [comment]
Thank you!

**Comment by adamyanalunas** [comment]
Thanks, @ksuther! No rush but any idea on a timeline for a release that contains this change?

**Pull request merged**
