### PR TITLE
Add pry byebug

### PR DESCRIPTION
**Pull request by guidomb**
When I forked the project to fix a bug I try to run a slather by doing

```
./bin/slather coverage -s PATH_TO_MY_PROJECT
```

but this generated errors when trying to require local files. That is why is used `require_relative`. Also I needed to debug the gem and I thought it would be practical for future contributors to have byebug and pry already installed as development dependencies.

### CODE REVIEW

**Comment by bootstraponline** [comment]
I like the require_relative change. I don't think we want pry/byebug as dev dependencies.

**Comment by sbhklr** [comment]
I agree with @bootstraponline. I think we should keep the dev dependencies as small as possible unless required by the CI build. However, I also like the `require_relative` changes. @guidomb Do you want to give it another shot or shall we close the PR?

**Comment by guidomb** [comment]
I'll give it try but after the next 2 weeks, I'm super busy with work.

**Comment by bootstraponline** [comment]
If you have time, feel free to submit a new pull request. I'm closing this one for now.

**Pull request closed without merging**
