### PR TITLE
Update nokogiri to 1.11

### PR DESCRIPTION
**Pull request by ashin-omg**
Nokogiri < 1.11 is vulnerable to XML External Entity (XXE) Injection 
https://snyk.io/vuln/SNYK-RUBY-NOKOGIRI-1055008

### CODE REVIEW

**Comment by matcartmill** [comment]
@ksuther can this get reviewed when you have a moment? My security gets a digest of all issues reported and this one is flagged. Would love to tell them it's in progress.

Thanks.

**Comment by danl3v** [comment]
This would be great to have in. Thanks!

**Comment by matcartmill** [comment]
@ksuther can we get an update please?

**Comment by ksuther** [comment]
Thanks for the PR! I'll make a new release in the next week or so as well.

**Pull request merged**
