### PR TITLE
Add relevant lines count and tested lines count to html report

### PR DESCRIPTION
**Pull request by SiemianHS**
### Background story
In the project where multiple modules are created, having just the code coverage percentage per module is not enough information to calculate the overall code coverage for the whole project. Additional information about total number of lines and total number of lines tested is required.

### PR description
In this PR additional data regarding total number of lines and total number of lines tested is added to html report.

### Screen shot
Zrzut ekranu 2021-04-24 o 11 21 10

### CODE REVIEW

**Comment by ksuther** [comment]
Thanks for the PR! Since this is showing the count for Total Coverage, would it make more sense to put the line count on the same line as Total Coverage?

For example, something like:

> Total Coverage : 94.37% (218 of 231 lines)

**Comment by SiemianHS** [comment]
Why i have not thought of that? 🤔 
Great suggestion, thanks  @ksuther. I will apply it.

**Comment by SiemianHS** [comment]
Updated according to your suggestion @ksuther, thank you for it and for all the hard work on Slather.
Zrzut ekranu 2021-04-29 o 15 52 10

**Comment by ksuther** [comment]
Thanks for the change! The bad news is you flipped the order of the variables. It should be 218 of 231 :)

**Comment by SiemianHS** [comment]
Shame on me, looks like i had some kind of brain fart when writing this. Thanks for spotting the issue. Now it's fixed.

**Comment by ksuther** [comment]
Thanks for the PR!

**Pull request merged**
