### PR TITLE
Add GitHub actions

### LINKED ISSUE #458: Support Github Actions
Would it be possible to support GithubActions and Coveralls?

https://github.com/SlatherOrg/slather/blob/69b74115aa3e0166230332e548d81aaeb669c973/lib/slather/coverage_service/coveralls.rb

### PR DESCRIPTION
**Pull request by troyfontaine**
My org uses Slather and I'd really like to try and contribute to bring support for Github Actions.

I'll apologize up front-I don't code in Ruby that much, so I'm completely open to feedback and whatever changes you would like to see 😄 

Closes #458

### CODE REVIEW

**Comment by ksuther** [comment]
Thanks for the contribution! I don't use GitHub Actions so I can't fully test it out, but this looks reasonable to me.

Are there any GitHub Actions users out there that can give these changes a try? If not I'm willing to merge it and include it in an update and fix if necessary, but always better to fix before the fact if possible :)

**Comment by troyfontaine** [comment]
> Thanks for the contribution! I don't use GitHub Actions so I can't fully test it out, but this looks reasonable to me.
> 
> Are there any GitHub Actions users out there that can give these changes a try? If not I'm willing to merge it and include it in an update and fix if necessary, but always better to fix before the fact if possible :)

I'm going to see if I can test it myself, but if there is anyone else that can lend a hand that would be great 😄

**Comment by 3a4oT** [comment]
When it can be merged and released?

**Comment by cnotethegr8** [comment]
I tried running this,

  ```
  run_tests(
    scheme: scheme,
    code_coverage: true
  )

  slather(
    scheme: scheme,
    proj: "MyApp.xcodeproj",
    coveralls: true
  )
```
 and got the following error,

> /Users/-/.rvm/gems/ruby-2.6.3/bundler/gems/slather-78a5905c9a4c/lib/slather/command/coverage_command.rb:94:in `setup_service_name': undefined method `github?' for #<CoverageCommand:0x00007ffd29b6f2a0> (NoMethodError)

Is my setup wrong or is this PR missing something?

**Review by martin-key — CHANGES_REQUESTED** [review]
Great work so far!
Few things:
1. in `coverage_command.rb` this needs to be added - `option ["--github"], :flag, "Indicate that the builds are running on Github Actions"` 
2. Coveralls API still doesn't support `github action` - https://docs.coveralls.io/api-introduction 

for the test if you change the name of `:service_name` in `coverage_service/coveralls.rb def coveralls_coverage_data` to `"circleci"` it will start working correctly. In all other cases it will crash with `Error while uploading coverage data to Coveralls. CI Service: github Message: Couldn't find a repository matching this job. (StandardError)`

**Comment by martin-key** [comment]
I have opened a new PR which is implementing the complete functionality - https://github.com/SlatherOrg/slather/pull/468

**Comment by troyfontaine** [comment]
Thanks @martin-key for picking this up!  I didn't have time the last few days to integrate your feedback.  I'll close my PR.

**Comment by martin-key** [comment]
@troyfontaine thanks!

**Pull request closed without merging**
