### PR TITLE
Optimize performance for many binaries

### PR DESCRIPTION
**Pull request by cltnschlosser**

### CODE REVIEW

**Comment by ksuther** [comment]
Thanks for the PR! Travis is failing (not sure why the check isn't appearing). Can you verify that the tests pass with your changes?

https://travis-ci.org/github/SlatherOrg/slather/builds/678206992

**Comment by cltnschlosser** [comment]
Looks like I broke some tests, looking into them now.

**Comment by cltnschlosser** [comment]
@ksuther Passing now :)

**Comment by ksuther** [comment]
Thanks! I'll push out a gem update with this included when I get a moment.

**Pull request merged**
