### PR TITLE
Added --travispro flag

### PR DESCRIPTION
**Pull request by sbhklr**
Implements #219

### CODE REVIEW

**Comment by neonichu** [comment]
Thanks, could you please add an entry to the changelog as well? Then it is good to go :+1:

**Comment by sbhklr** [comment]
@neonichu Done.

**Comment by neonichu** [comment]
Thanks for the contribution :+1:

**Comment by neonichu** [comment]
Also thanks for answering issues :) Let me know if you want to be added to the slather GitHub org.

**Comment by sbhklr** [comment]
@neonichu Not a problem. Sure, I'd be glad to be a slather member 🙌

**Pull request merged**
