### PR TITLE
Xcode 16 beta 5 compatibility

### LINKED ISSUE #567: Slather failing with Xcode 16 beta 4
With Xcode 16 beta 4 and Xcode 16 beta 5 I get the following error:

```sh
/opt/homebrew/Cellar/ruby/3.3.4/lib/ruby/3.3.0/json/common.rb:219:in `parse': unexpected token at '' (JSON::ParserError)
	from /opt/homebrew/Cellar/ruby/3.3.4/lib/ruby/3.3.0/json/common.rb:219:in `parse'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/lib/slather/project.rb:135:in `pathnames_per_binary'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/lib/slather/project.rb:124:in `block in profdata_coverage_files'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/lib/slather/project.rb:123:in `each'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/lib/slather/project.rb:123:in `profdata_coverage_files'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/lib/slather/project.rb:98:in `coverage_files'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/lib/slather/coverage_service/cobertura_xml_output.rb:18:in `post'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/lib/slather/command/coverage_command.rb:108:in `post'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/lib/slather/command/coverage_command.rb:64:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/slather-2.8.3/bin/slather:17:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.3.0/bin/slather:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.3.0/bin/slather:25:in `<main>'
```

I assume the format has changed. I'm not sure how to find the source coverage file that is causing the problem.

### PR DESCRIPTION
**Pull request by ksuther**
`find_binary_file_in_bundle` will now look for and prefer .debug.dylib binaries, which is what Xcode 16 generates to support new Xcode features.

This new behavior in Xcode 16 can be disabled by setting `ENABLE_DEBUG_DYLIB=NO` (see https://developer.apple.com/documentation/xcode/build-settings-reference#Enable-Debug-Dylib-Support).

Fixes #567.

It'd be great if someone else can give this a try and see if it works for them (@jarrodlombardo-EventBase @OliverBrown-Next).

### CODE REVIEW

**Review by jarrodlombardo-EventBase — APPROVED** [review]
This still works fine in XCode 15. I can't use 16 on my machine yet, so I don't know if it fixes things there.

**Comment by alfredofernandes** [comment]
This fixes #567 in our code base as well running Xcode 16 beta 6. @ksuther

**Comment by SergeyPetrachkov** [comment]
Any ETA on when the fixes will be available in the new version? 👀

**Comment by ksuther** [comment]
I'll try to get a release out later this week.

**Comment by SergeyPetrachkov** [comment]
> I'll try to get a release out later this week.

Nice! Much appreciated!

**Comment by ksuther** [comment]
Released in 2.8.4.

**Pull request merged**
