### PR TITLE
Simple JSON output.

### PR DESCRIPTION
**Pull request by ileitch**

### CODE REVIEW

**Comment by ksuther** [comment]
Thanks for the PR! What is the JSON output used for? Is it for an input to another internal tool or is there some service that uses JSON as the input format?

**Comment by ileitch** [comment]
I'm using it to communicate with Coveralls directly outside of Slather, as Slather wasn't quite appropriate for my use case.

I figured since it's also super basic, it might be useful for other people to use as a basis if Slather doesn't already support their desired format.

**Comment by ksuther** [comment]
Got it, thanks. Good to have a use case documented in case anyone else stumbles upon it later.

Could you update the changelog in the PR and I'll merge it?

**Comment by ileitch** [comment]
Updated.

**Comment by ksuther** [comment]
Thanks!

**Pull request merged**
