### PR TITLE
Add --decimals flag for HTML and simple output

### LINKED ISSUE #205: Configurable precision in percentage results
[`%.2f` is hard coded](https://github.com/SlatherOrg/slather/search?utf8=%E2%9C%93&q=2f&type=Code) in both the simple output and html output. For large projects, it's helpful to have more accurate percentage values. Thoughts on adding a command line option to adjust the float rounding?

### PR DESCRIPTION
**Pull request by bootstraponline**
.to_f is used to avoid excessive zeros.
0.0000.to_f => 0.0

Fix #205

### CODE REVIEW

**Comment by neonichu** [comment]
Thanks for this PR, it has some conflicts with your other one (#208), could you please rebase it?

**Comment by bootstraponline** [comment]
Rebased.

**Comment by neonichu** [comment]
Awesome, thanks a lot for this PR and the other contributions, like answering some issues. 

If you are interested, I would like to add you as a member to the GitHub team. This obviously comes with no obligations to contribute further in the future :)

**Comment by bootstraponline** [comment]
> If you are interested, I would like to add you as a member to the GitHub team. This obviously comes with no obligations to contribute further in the future :)

Sure, I'd be happy to join.

**Pull request merged**
