### PR TITLE
Refactor bin/slather to use named subclasses

### PR DESCRIPTION
**Pull request by bootstraponline**
Clamp's auto generation of an anonymous subclass for the commands makes programmatic usage of commands difficult. Explicit subcommand classes allow running commands directly without having to create a new process per command.

Per the use case described in https://github.com/SlatherOrg/slather/issues/96#issuecomment-195054111, it'd be nice to invoke the coverage command multiple times without having to spawn a new process.

### CODE REVIEW

**Comment by neonichu** [comment]
LGTM, could you add a changelog entry as well, please?

**Comment by bootstraponline** [comment]
Sure, I'll update this PR later today.

**Comment by bootstraponline** [comment]
Updated the change log.

**Comment by neonichu** [comment]
awesome, thank you — will merge once build is green.

**Pull request merged**
