### PR TITLE
Add support for Sonarqube generic code coverage output

### LINKED ISSUE #258: Slather Cobertura report  integration  with Sonarqube  4.5.7
Has any one  integrated the cobertura.xml  file with the sonarqube  4.5.7

Using Slather 2.3.0
Using Xcode 7+

while running the  generated cobertura.xml against sonar the below error is generated 

 ERROR: Caused by: Error at line 3 of coverage report path to file /slather-report/cobertura.xml
 ERROR: Caused by: Unknown coverage version: Slather 2.3.0. This parser only handles version 1.

The first 3 lines in the file that is generated
<?xml version="1.0"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<coverage line-rate="0.0995231183910429" branch-rate="1.0000000000000000" lines-covered="960" lines-valid="9646" branches-covered="0" branches-valid="0" complexity="0.0" timestamp="1476702379" version="Slather 2.3.0">

Thanks in advance

### PR DESCRIPTION
**Pull request by adellibovi**
Hello 👋 

This PR add support for Sonarqube generic code coverage xml. 😄

I am not sure what's the policy for adding new output strategy, I hope this could fit in. 🙏 

Cheers,

Edited: probably this closes #258

### CODE REVIEW

**Comment by adellibovi** [comment]
Hi @ksuther, any chance you could look at this? 🙏

**Comment by ksuther** [comment]
Thanks for the contribution! I'll take your word that it actually works with Sonarqube, as I've never used it :)

**Comment by adellibovi** [comment]
Thank you @ksuther 😊 Do you know when new releases are usually planned?

**Comment by arturonaredo** [comment]
@adellibovi Do you know if this PR works with newer versions of SonarQube? since the issue linked is from 4 years ago... I bet you tested with a newer version. I'm in 8.2

**Comment by arturonaredo** [comment]
@ksuther this deserves a release indeed!! :)

**Comment by adellibovi** [comment]
Thanks @arturonaredo, I tested with 8.1 😊

**Comment by arturonaredo** [comment]
I have build the gem after cloning with 'rake build' and installed with 'sudo gem install pkg/slather-2.4.8.gem'. Works for me in the meantime while the official release is done. 

Working as expected. 

XCode 11.4.1
SonarQube Version 8.2 (build 32929) EE

**Comment by adellibovi** [comment]
@arturonaredo I wonder how fast was for you with this approach vs what Sonarqube is suggesting? To me it was almost 2 hours vs seconds :)

**Comment by TuiMobilityHub** [comment]
I've tested also with SonarCloud and it's working fine.

**Comment by arturonaredo** [comment]
@adellibovi You tell me... I was totally blocked because I got an error. After a month of other tasks I found this and... owe you a social distanced beer! moltes gràcies

**Comment by rmaqueda** [comment]
I've tried also in SonarCloud and it's working fine.

**Comment by ksuther** [comment]
I'll try to do a release in the next few days. Thanks for the confirmations that it works!

**Comment by albsala** [comment]
Let's do this guys 👍  fastlane/fastlane#16500

**Comment by Unknoob** [comment]
We've been using the `Cobertura.xml` output for Sonar for months and it works. What's exactly the difference with this new format?

**Comment by ksuther** [comment]
Released in Slather 2.4.9!

**Comment by rmaqueda** [comment]
> Released in Slather 2.4.9!

Sorry for this question, maybe I'm doing something wrong with rubygems but I'm trying to update via `gem update slather` and I'm getting the previous version 2.4.8.

Do I need to do something extra to get the 2.4.9 version?

Thanks.

**Comment by ksuther** [comment]
Sorry about that, please try again. I ran `rake release` but didn't realize it had hung and didn't finish.

**Comment by jaderYang** [comment]
Thanks a lot. @ksuther

**Pull request merged**
